# Generated by Django 2.0.4 on 2018-05-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0002_auto_20180511_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='youTubeURL',
            field=models.URLField(default='www.youtube.com'),
        ),
    ]
